export const ActionType = {
    NEW_USER: 'NEW_USER',
    GET_WASTE: 'GET_WASTE',
    WASTE_SELECTED: 'WASTE_SELECTED',
    WAST_DROPPED: 'WAST_DROPPED',
    CAST_BLUE: 'CAST_BLUE',
    CAST_YELLOW: 'CAST_YELLOW',
    CAST_MARRON: 'CAST_MARRON',
    CAST_GREEN: 'CAST_GREEN',
    UPDATE_SCORE: 'UPDATE_SCORE'

}